name: test-find-commit

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/test-find-commit.yml

jobs:
  test:
    runs-on: ubuntu-latest
    # outputs:
    #   updateable: ${{ steps.check_update.outputs.updateable}}
    #   jobsinfo: ${{ steps.check_update.outputs.jobsinfo}}
    steps:
      - name: Configure git
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v7

      - name: find commit id
        uses: peter-evans/find-comment@v4.0.0
        id: fc
        with:
          repository: lsq/msys2-packages
          issue-number: 7
          body-includes: Failed build package list

      - name: print commit id
        run: |
          echo ${{ steps.fc.outputs.comment-id }}
          echo ${{ steps.fc.outputs.comment-node-id }}
          echo ${{ steps.fc.outputs.comment-body }}
          echo ${{ steps.fc.outputs.comment-author }}
          echo ${{ steps.fc.outputs.comment-created-at }}
